development: &development
  adapter: mysql2
  database: scout_development
  pool: 5
  username: marcel
  password:
staging: 
  <<: *development
test:
  adapter: mysql2
  database: scout_test
  pool: 5
  username: marcel
  password:
production:
  adapter: mysql2
  database: scout_production
  pool: 10
  username: scout
  password: secret
